import type { ReadinessCategory, SignalSeverity } from '../domain';

export type SensitivePathMatcher = 'glob' | 'regex';

export interface SensitivePathRule {
  id: string;
  category: ReadinessCategory;
  matcher: SensitivePathMatcher;
  pattern: string;
  severityHint: SignalSeverity;
  explanation: string;
}

const DEFAULT_SENSITIVE_PATH_RULES: readonly SensitivePathRule[] = [
  {
    id: 'auth-directory',
    category: 'identity_access',
    matcher: 'glob',
    pattern: '**/auth/**',
    severityHint: 'high',
    explanation: 'Authentication code can change sign-in and access behavior.',
  },
  {
    id: 'middleware-file',
    category: 'identity_access',
    matcher: 'glob',
    pattern: '**/middleware.*',
    severityHint: 'high',
    explanation: 'Middleware can change sessions, routing, or protected access.',
  },
  {
    id: 'session-file',
    category: 'identity_access',
    matcher: 'glob',
    pattern: '**/session*.*',
    severityHint: 'high',
    explanation: 'Session handling affects authentication persistence and access.',
  },
  {
    id: 'login-directory',
    category: 'identity_access',
    matcher: 'glob',
    pattern: '**/login/**',
    severityHint: 'medium',
    explanation: 'Login routes and components are part of the identity surface.',
  },
  {
    id: 'signup-directory',
    category: 'identity_access',
    matcher: 'glob',
    pattern: '**/signup/**',
    severityHint: 'medium',
    explanation: 'Signup routes and components are part of the identity surface.',
  },
  {
    id: 'admin-directory',
    category: 'identity_access',
    matcher: 'glob',
    pattern: '**/admin/**',
    severityHint: 'high',
    explanation: 'Admin paths commonly carry privileged access behavior.',
  },
  {
    id: 'protected-directory',
    category: 'identity_access',
    matcher: 'glob',
    pattern: '**/protected*/**',
    severityHint: 'high',
    explanation: 'Protected paths commonly depend on authorization checks.',
  },
  {
    id: 'prisma-directory',
    category: 'data_persistence',
    matcher: 'glob',
    pattern: '**/prisma/**',
    severityHint: 'high',
    explanation: 'Prisma files can change schemas, migrations, or database access.',
  },
  {
    id: 'drizzle-directory',
    category: 'data_persistence',
    matcher: 'glob',
    pattern: '**/drizzle/**',
    severityHint: 'high',
    explanation: 'Drizzle files can change schemas, migrations, or database access.',
  },
  {
    id: 'migrations-directory',
    category: 'data_persistence',
    matcher: 'glob',
    pattern: '**/migrations/**',
    severityHint: 'high',
    explanation: 'Migration files can change persisted production data.',
  },
  {
    id: 'schema-file',
    category: 'data_persistence',
    matcher: 'glob',
    pattern: '**/schema.*',
    severityHint: 'high',
    explanation: 'Schema files define persisted data contracts.',
  },
  {
    id: 'supabase-directory',
    category: 'data_persistence',
    matcher: 'glob',
    pattern: '**/supabase/**',
    severityHint: 'high',
    explanation: 'Supabase paths can affect database, storage, or auth persistence.',
  },
  {
    id: 'firebase-directory',
    category: 'data_persistence',
    matcher: 'glob',
    pattern: '**/firebase/**',
    severityHint: 'high',
    explanation: 'Firebase paths can affect stored data and service configuration.',
  },
  {
    id: 'database-directory',
    category: 'data_persistence',
    matcher: 'regex',
    pattern: '(^|/)(?:db|database)(/|$)',
    severityHint: 'high',
    explanation: 'Database paths can change persistence behavior.',
  },
  {
    id: 'storage-upload-directory',
    category: 'data_persistence',
    matcher: 'regex',
    pattern: '(^|/)(?:storage|uploads?)(/|$)',
    severityHint: 'medium',
    explanation: 'Storage and upload paths can change persisted files or objects.',
  },
  {
    id: 'root-env-file',
    category: 'secrets_config',
    matcher: 'glob',
    pattern: '.env*',
    severityHint: 'high',
    explanation: 'Environment files can expose or change production configuration.',
  },
  {
    id: 'nested-env-file',
    category: 'secrets_config',
    matcher: 'glob',
    pattern: '**/.env*',
    severityHint: 'high',
    explanation: 'Environment files can expose or change production configuration.',
  },
  {
    id: 'config-directory',
    category: 'secrets_config',
    matcher: 'glob',
    pattern: '**/config/**',
    severityHint: 'medium',
    explanation: 'Configuration paths can alter production behavior.',
  },
  {
    id: 'framework-config-file',
    category: 'secrets_config',
    matcher: 'regex',
    pattern: '(^|/)(?:next|vite|astro|nuxt)\\.config\\.[^/]+$',
    severityHint: 'medium',
    explanation: 'Framework configuration can alter build and runtime behavior.',
  },
  {
    id: 'github-workflow',
    category: 'deployment_ops',
    matcher: 'glob',
    pattern: '.github/workflows/**',
    severityHint: 'high',
    explanation: 'GitHub workflows can change CI or deployment automation.',
  },
  {
    id: 'vercel-config',
    category: 'deployment_ops',
    matcher: 'glob',
    pattern: 'vercel.json',
    severityHint: 'high',
    explanation: 'Vercel configuration can change production deployment behavior.',
  },
  {
    id: 'netlify-config',
    category: 'deployment_ops',
    matcher: 'glob',
    pattern: 'netlify.toml',
    severityHint: 'high',
    explanation: 'Netlify configuration can change production deployment behavior.',
  },
  {
    id: 'dockerfile',
    category: 'deployment_ops',
    matcher: 'regex',
    pattern: '(^|/)Dockerfile(?:\\.[^/]+)?$',
    severityHint: 'high',
    explanation: 'Docker build instructions can change production runtime behavior.',
  },
  {
    id: 'docker-compose-config',
    category: 'deployment_ops',
    matcher: 'glob',
    pattern: 'docker-compose.*',
    severityHint: 'high',
    explanation: 'Docker Compose configuration can change deployed services.',
  },
  {
    id: 'wrangler-config',
    category: 'deployment_ops',
    matcher: 'glob',
    pattern: 'wrangler.*',
    severityHint: 'high',
    explanation: 'Wrangler configuration can change Cloudflare deployment behavior.',
  },
  {
    id: 'package-lockfile',
    category: 'deployment_ops',
    matcher: 'regex',
    pattern:
      '(^|/)(?:bun\\.lockb?|npm-shrinkwrap\\.json|package-lock\\.json|pnpm-lock\\.yaml|yarn\\.lock)$',
    severityHint: 'medium',
    explanation: 'Package manager lockfiles determine installed production dependencies.',
  },
  {
    id: 'integration-service-directory',
    category: 'external_integrations',
    matcher: 'regex',
    pattern:
      '(^|/)(?:stripe|paypal|billing|webhooks?|email|resend|sendgrid|twilio|openai|anthropic|analytics)(/|$)',
    severityHint: 'high',
    explanation: 'Third-party integration paths can change credentials and failure behavior.',
  },
  {
    id: 'app-page-route',
    category: 'public_surface',
    matcher: 'glob',
    pattern: '**/app/**/page.*',
    severityHint: 'medium',
    explanation: 'Application page files can add or change public routes.',
  },
  {
    id: 'app-api-route',
    category: 'public_surface',
    matcher: 'glob',
    pattern: '**/app/**/route.*',
    severityHint: 'high',
    explanation: 'Application route handlers can add or change public endpoints.',
  },
  {
    id: 'pages-directory',
    category: 'public_surface',
    matcher: 'glob',
    pattern: '**/pages/**',
    severityHint: 'medium',
    explanation: 'Pages paths can add or change public routes.',
  },
  {
    id: 'routes-directory',
    category: 'public_surface',
    matcher: 'glob',
    pattern: '**/routes/**',
    severityHint: 'medium',
    explanation: 'Route paths can add or change public application surfaces.',
  },
  {
    id: 'api-directory',
    category: 'public_surface',
    matcher: 'glob',
    pattern: '**/api/**',
    severityHint: 'high',
    explanation: 'API paths can add or change externally reachable endpoints.',
  },
  {
    id: 'public-route-name',
    category: 'public_surface',
    matcher: 'regex',
    pattern:
      '(^|/)(?:login|signup|admin|dashboard|billing|settings|callback|webhooks?|uploads?)(/|$)',
    severityHint: 'medium',
    explanation: 'Named route paths commonly expose user-visible or callback surfaces.',
  },
  {
    id: 'test-file',
    category: 'testing_recovery',
    matcher: 'regex',
    pattern: '\\.(?:test|spec)\\.[^/]+$',
    severityHint: 'low',
    explanation: 'Test file changes affect verification and recovery confidence.',
  },
  {
    id: 'test-directory',
    category: 'testing_recovery',
    matcher: 'regex',
    pattern: '(^|/)(?:__tests__|tests?|e2e|cypress|playwright)(/|$)',
    severityHint: 'low',
    explanation: 'Test directory changes affect verification and recovery confidence.',
  },
  {
    id: 'test-runner-config',
    category: 'testing_recovery',
    matcher: 'regex',
    pattern: '(^|/)(?:playwright|cypress|vitest)\\.config\\.[^/]+$',
    severityHint: 'medium',
    explanation: 'Test runner configuration can change verification coverage.',
  },
  {
    id: 'ci-workflow',
    category: 'testing_recovery',
    matcher: 'glob',
    pattern: '.github/workflows/**',
    severityHint: 'medium',
    explanation: 'Workflow changes can alter continuous verification and recovery checks.',
  },
  {
    id: 'backup-copy-file',
    category: 'maintainability',
    matcher: 'regex',
    pattern: '(^|/)[^/]*(?:^|[._-])(?:backup|copy|temp|old|orig)(?:[._-]|$)[^/]*$',
    severityHint: 'low',
    explanation: 'Backup, copy, and temporary-looking files can increase maintenance burden.',
  },
];

export function getSensitivePathRules(): SensitivePathRule[] {
  return DEFAULT_SENSITIVE_PATH_RULES.map((rule) => ({ ...rule }));
}
