import type {
  EvidenceRef,
  ReadinessCategory,
  ReadinessSnapshot,
  ReadinessState,
  SnapshotConfidence,
} from '../domain';
import { redactEvidenceRef } from '../redaction';

export interface AdcFixHandoffOptions {
  includeCompareUrl?: boolean;
  includeHistory?: boolean;
  includeAdcFixLink?: boolean;
  redactPathNames?: boolean;
}

const RECEIPT_STATIC_LIMITATION =
  'This is a static readiness snapshot. It does not run the app, execute tests, or prove correctness.';

const HANDOFF_STATIC_LIMITATION =
  'Generated by deterministic static checks. It does not run the app or prove correctness. No source code, ZIP, or report content was uploaded by B2G.';

const CATEGORY_LABELS: Readonly<Record<ReadinessCategory, string>> = {
  identity_access: 'Identity and access',
  data_persistence: 'Data and persistence',
  secrets_config: 'Secrets and configuration',
  deployment_ops: 'Deployment and operations',
  external_integrations: 'External integrations',
  public_surface: 'Public surface',
  testing_recovery: 'Testing and recovery',
  maintainability: 'Maintainability',
  change_history: 'Change history',
};

function compareCodePoints(left: string, right: string): number {
  if (left < right) {
    return -1;
  }
  if (left > right) {
    return 1;
  }
  return 0;
}

function titleCase(value: ReadinessState | SnapshotConfidence): string {
  return `${value.slice(0, 1).toUpperCase()}${value.slice(1)}`;
}

function normalizeInlineText(value: string): string {
  return value.replace(/\s+/g, ' ').trim();
}

function escapeMarkdownText(value: string): string {
  return normalizeInlineText(value)
    .replace(/\\/g, '\\\\')
    .replace(/([[\]*_<>#|])/g, '\\$1');
}

function inlineCode(value: string): string {
  const normalized = normalizeInlineText(value);
  const longestBacktickRun = Math.max(
    0,
    ...[...normalized.matchAll(/`+/g)].map((match) => match[0].length)
  );
  const fence = '`'.repeat(longestBacktickRun + 1);
  const content =
    normalized.startsWith('`') || normalized.endsWith('`') ? ` ${normalized} ` : normalized;
  return `${fence}${content}${fence}`;
}

function sentence(value: string): string {
  const text = escapeMarkdownText(value);
  return /[.!?]$/.test(text) ? text : `${text}.`;
}

function yesNo(value: boolean): string {
  return value ? 'Yes' : 'No';
}

function addOptionalMetric(lines: string[], label: string, value: number | undefined): void {
  if (value !== undefined) {
    lines.push(`- ${label}: ${value.toLocaleString('en-US')}`);
  }
}

function renderBulletList(values: readonly string[], emptyText = 'None reported.'): string[] {
  if (values.length === 0) {
    return [`- ${emptyText}`];
  }
  return values.map((value) => `- ${escapeMarkdownText(value)}`);
}

function renderNumberedList(values: readonly string[]): string[] {
  if (values.length === 0) {
    return ['- None reported.'];
  }
  return values.map((value, index) => `${index + 1}. ${escapeMarkdownText(value)}`);
}

function uniqueLimitations(snapshot: ReadinessSnapshot, staticLimitation: string): string[] {
  return [...new Set([...snapshot.limitations, staticLimitation])];
}

function sanitizedEvidence(evidence: readonly EvidenceRef[]): EvidenceRef[] {
  return evidence.map((item) => redactEvidenceRef(item));
}

function evidencePaths(snapshot: ReadinessSnapshot): string[] {
  const paths = new Set<string>();
  const groups = [
    ...snapshot.categories.map((category) => category.evidence),
    ...snapshot.signals.map((signal) => signal.evidence),
    ...(snapshot.trends?.map((trend) => trend.evidence) ?? []),
  ];
  for (const evidence of groups.flat()) {
    if (evidence.path) {
      paths.add(evidence.path);
    }
  }
  return [...paths].sort(
    (left, right) => right.length - left.length || compareCodePoints(left, right)
  );
}

function redactRenderedPaths(markdown: string, snapshot: ReadinessSnapshot): string {
  let redacted = markdown;
  for (const path of evidencePaths(snapshot)) {
    const escapedPath = escapeMarkdownText(path);
    redacted = redacted.replaceAll(escapedPath, '[path redacted]');
    if (escapedPath !== path) {
      redacted = redacted.replaceAll(path, '[path redacted]');
    }
  }
  return redacted;
}

export function sanitizeMarkdownEvidence(snapshot: ReadinessSnapshot): ReadinessSnapshot {
  return {
    ...snapshot,
    repository: { ...snapshot.repository },
    base: { ...snapshot.base },
    candidate: { ...snapshot.candidate },
    comparison: { ...snapshot.comparison },
    state: {
      ...snapshot.state,
      topConcerns: [...snapshot.state.topConcerns],
      safeLookingAreas: [...snapshot.state.safeLookingAreas],
    },
    categories: snapshot.categories.map((category) => ({
      ...category,
      evidence: sanitizedEvidence(category.evidence),
    })),
    signals: snapshot.signals.map((signal) => ({
      ...signal,
      evidence: sanitizedEvidence(signal.evidence),
    })),
    trends: snapshot.trends?.map((trend) => ({
      ...trend,
      evidence: sanitizedEvidence(trend.evidence),
    })),
    outputs: {},
    limitations: [...snapshot.limitations],
  };
}

function renderEvidence(evidence: readonly EvidenceRef[], redactPathNames: boolean): string {
  if (evidence.length === 0) {
    return '';
  }

  const rendered = evidence.map((item) => {
    const label = escapeMarkdownText(item.label);
    if (!item.path) {
      return label;
    }
    const path = redactPathNames ? '[path redacted]' : item.path;
    return `${label} (${inlineCode(path)})`;
  });
  return ` Evidence: ${rendered.join('; ')}.`;
}

export function generateExportReceiptMarkdown(snapshot: ReadinessSnapshot): string {
  const safeSnapshot = sanitizeMarkdownEvidence(snapshot);
  const { comparison, state } = safeSnapshot;
  const lines = [
    '# Bolt Export Receipt',
    '',
    `Readiness: ${titleCase(state.state)}`,
    `Confidence: ${titleCase(state.confidence)}`,
    `Generated: ${escapeMarkdownText(safeSnapshot.generatedAt)}`,
    `Repository: ${escapeMarkdownText(
      `${safeSnapshot.repository.owner}/${safeSnapshot.repository.name}`
    )}`,
    `Compared against: ${escapeMarkdownText(`${safeSnapshot.base.ref}@${safeSnapshot.base.sha}`)}`,
    `Candidate export: ${escapeMarkdownText(safeSnapshot.candidate.id)}`,
    '',
    '## Summary',
    '',
    escapeMarkdownText(state.headline),
    '',
    escapeMarkdownText(state.recommendedAction),
    '',
    '## Change metrics',
    '',
    `- Files changed: ${comparison.changedFiles.toLocaleString('en-US')}`,
    `- Files added: ${comparison.addedFiles.toLocaleString('en-US')}`,
    `- Files deleted: ${comparison.deletedFiles.toLocaleString('en-US')}`,
  ];

  addOptionalMetric(lines, 'Files renamed', comparison.renamedFiles);
  addOptionalMetric(lines, 'Lines added', comparison.addedLines);
  addOptionalMetric(lines, 'Lines deleted', comparison.deletedLines);
  lines.push(
    `- Binary files changed: ${comparison.binaryFilesChanged.toLocaleString('en-US')}`,
    `- Sensitive files changed: ${comparison.sensitiveFilesChanged.toLocaleString('en-US')}`,
    `- Package manifest changed: ${yesNo(comparison.packageManifestChanged)}`,
    `- Lockfile changed: ${yesNo(comparison.lockfileChanged)}`,
    `- Environment example changed: ${yesNo(comparison.envExampleChanged)}`,
    `- Public route surface changed: ${yesNo(comparison.routeSurfaceChanged)}`,
    '',
    '## Top concerns',
    '',
    ...renderNumberedList(state.topConcerns),
    '',
    '## Safe-looking areas',
    '',
    ...renderBulletList(state.safeLookingAreas),
    '',
    '## Limitations',
    '',
    ...renderBulletList(uniqueLimitations(safeSnapshot, RECEIPT_STATIC_LIMITATION))
  );

  return `${lines.join('\n')}\n`;
}

function renderChangedAreas(snapshot: ReadinessSnapshot, redactPathNames: boolean): string[] {
  if (snapshot.categories.length === 0) {
    return ['- None reported.'];
  }

  const lines: string[] = [];
  for (const category of snapshot.categories) {
    lines.push(`### ${CATEGORY_LABELS[category.category]}`, '');
    const signals = snapshot.signals.filter((signal) => signal.category === category.category);
    if (signals.length === 0) {
      lines.push('- No detailed signals were available.', '');
      continue;
    }
    for (const signal of signals) {
      lines.push(
        `- ${escapeMarkdownText(signal.title)} — ${sentence(signal.message)}${renderEvidence(
          signal.evidence,
          redactPathNames
        )}`
      );
    }
    lines.push('');
  }
  lines.pop();
  return lines;
}

function renderHistoricalContext(snapshot: ReadinessSnapshot, redactPathNames: boolean): string[] {
  if (!snapshot.trends || snapshot.trends.length === 0) {
    return ['- No historical trends were available.'];
  }
  return [...snapshot.trends]
    .sort((left, right) => compareCodePoints(left.id, right.id))
    .map((trend) => `- ${sentence(trend.label)}${renderEvidence(trend.evidence, redactPathNames)}`);
}

function suggestedReviewAreas(snapshot: ReadinessSnapshot): string[] {
  const reviews = new Set(
    snapshot.signals
      .map((signal) => signal.suggestedReview)
      .filter((review): review is string => Boolean(review))
  );
  if (reviews.size === 0) {
    reviews.add(snapshot.state.recommendedAction);
  }
  return [...reviews].sort(compareCodePoints);
}

export function generateAdcFixHandoffMarkdown(
  snapshot: ReadinessSnapshot,
  options: AdcFixHandoffOptions
): string {
  const safeSnapshot = sanitizeMarkdownEvidence(snapshot);
  const includeCompareUrl = options.includeCompareUrl !== false;
  const includeHistory = options.includeHistory !== false;
  const redactPathNames = options.redactPathNames === true;
  const lines = [
    '# ADC Fix Handoff Report',
    '',
    '## Repository',
    '',
    `- Repository: ${escapeMarkdownText(
      `${safeSnapshot.repository.owner}/${safeSnapshot.repository.name}`
    )}`,
    `- Base ref: ${escapeMarkdownText(`${safeSnapshot.base.ref}@${safeSnapshot.base.sha}`)}`,
    `- Candidate export: ${escapeMarkdownText(safeSnapshot.candidate.id)}`,
  ];

  if (includeCompareUrl && safeSnapshot.base.compareUrl) {
    lines.push(`- Compare URL: ${escapeMarkdownText(safeSnapshot.base.compareUrl)}`);
  }

  lines.push(
    '',
    '## Readiness summary',
    '',
    `State: ${titleCase(safeSnapshot.state.state)}`,
    `Confidence: ${titleCase(safeSnapshot.state.confidence)}`,
    '',
    escapeMarkdownText(safeSnapshot.state.headline),
    '',
    escapeMarkdownText(safeSnapshot.state.recommendedAction),
    '',
    'This static snapshot highlights production-sensitive areas for suggested review. ADC Fix is optional, and no source code or report content was uploaded.',
    '',
    '## Changed areas',
    '',
    ...renderChangedAreas(safeSnapshot, redactPathNames)
  );

  if (includeHistory) {
    lines.push(
      '',
      '## Historical context',
      '',
      ...renderHistoricalContext(safeSnapshot, redactPathNames)
    );
  }

  lines.push(
    '',
    '## Suggested ADC Fix review areas',
    '',
    ...renderBulletList(suggestedReviewAreas(safeSnapshot)),
    '',
    '## Safe-looking areas',
    '',
    ...renderBulletList(safeSnapshot.state.safeLookingAreas),
    ''
  );

  if (options.includeAdcFixLink === true) {
    lines.push(
      '## Optional deeper review',
      '',
      '[Open ADC Fix](https://fix.aidrivencoder.com)',
      '',
      'Opening ADC Fix and sharing this report are explicit user actions.',
      ''
    );
  }

  lines.push(
    '## Limitations',
    '',
    ...renderBulletList(uniqueLimitations(safeSnapshot, HANDOFF_STATIC_LIMITATION))
  );

  const markdown = `${lines.join('\n')}\n`;
  return redactPathNames ? redactRenderedPaths(markdown, safeSnapshot) : markdown;
}
