name: Create Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v1.0.0)'
        required: true
        default: 'manual-build'

permissions:
  contents: write
  actions: read
  checks: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Set version
        id: version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          else
            echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
          fi

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Zip build artifacts
        run: |
          cd dist
          zip -r ../bolt-to-github-${{ env.VERSION }}.zip .

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: bolt-to-github-${{ env.VERSION }}.zip
          draft: false
          prerelease: false
          generate_release_notes: true
          tag_name: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version || github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
